<?php 
include 'db_connect.php'; 

$cloudinary_base = "https://res.cloudinary.com/dnsnpr8hu/image/upload/f_auto,q_auto/";

// Fetch Orders
$orders = [];
$orders_query = mysqli_query($conn, "SELECT * FROM tbl_orders WHERE delivery_instructions != 'POS Transaction' OR delivery_instructions IS NULL ORDER BY order_date DESC");
if ($orders_query) {
    while ($row = mysqli_fetch_assoc($orders_query)) {
        $order_id = $row['order_id'];
        $raw_type = strtolower($row['delivery_type'] ?: 'delivery');
        $type_display = ($raw_type === 'pickup' || $raw_type === 'pick up') ? 'Pick Up' : 'Delivery';
        
        $orders[$order_id] = [
            'id' => $order_id,
            'customer' => 'Customer #' . $order_id,
            'platform' => 'Website',
            'type' => $type_display,
            'price' => floatval($row['total_amount']),
            'status' => ucfirst($row['order_status'] ?: 'Pending'),
            'time' => date('M j, g:i A', strtotime($row['order_date'])),
            'payment_method' => $row['payment_method'],
            'delivery_instructions' => $row['delivery_instructions'],
            'items' => []
        ];
    }
}

// Fetch Items
$items_query = mysqli_query($conn, "
    SELECT oi.order_id, oi.quantity, oi.price_at_time, p.prod_name, p.prod_image 
    FROM tbl_order_items oi 
    LEFT JOIN tbl_products p ON oi.prod_id = p.prod_id
");
if ($items_query) {
    while ($row = mysqli_fetch_assoc($items_query)) {
        $order_id = $row['order_id'];
        if (isset($orders[$order_id])) {
            $orders[$order_id]['items'][] = [
                'name' => $row['prod_name'] ? $row['prod_name'] : 'Unknown Product',
                'quantity' => intval($row['quantity']),
                'price' => floatval($row['price_at_time']),
                'image' => $row['prod_image']
            ];
        }
    }
}

$orders_json = json_encode(array_values($orders));
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Orders - Paws&Keeps</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        .order-actions button {
            transition: transform 0.2s;
        }
        .order-actions button:hover {
            transform: scale(1.05);
        }
    </style>
</head>
<body>
    <div class="app-container">
        <aside class="sidebar">
            <div class="logo-container">
                <a href="index.php"><img src="<?php echo $cloudinary_base; ?>logo.png" onerror="this.src='https://res.cloudinary.com/dnsnpr8hu/image/upload/f_auto,q_auto/logo.png'" alt="Paws&Keeps Logo" class="brand-logo"></a>
            </div>
            <nav class="nav-menu">
                <div class="nav-header">
                    <a href="index.php" class="online-orders-link">
                        <h2 class="online-orders" style="color: #000;"><i class="fa-solid fa-arrow-left"></i> Back to POS</h2>
                    </a>
                    <hr class="nav-divider">
                </div>
                <div class="nav-group all-products-group">
                    <li class="filter-btn active"><i class="fa-solid fa-cart-shopping"></i> Online Orders</li>
                </div>
                <div class="nav-group all-products-group">
                    <a href="receipts.php" style="text-decoration:none;color:inherit;">
                        <li class="filter-btn"><i class="fa-solid fa-receipt"></i> Receipts</li>
                    </a>
                </div>
            </nav>
        </aside>

        <main class="main-wrapper orders-wrapper">
            <div class="orders-header">
                <div class="orders-tabs">
                    <button class="order-tab active" data-status="All">All Online Orders</button>
                    <button class="order-tab" data-status="Pending">Pending</button>
                    <button class="order-tab" data-status="Accepted">Accepted</button>
                    <button class="order-tab" data-status="Rejected">Rejected</button>
                    <button class="order-tab" data-status="Finished">Finished</button>
                </div>
                <div class="orders-user-info">
                    <i class="fa-regular fa-clock"></i> <span id="currentDateTime"></span>
                </div>
            </div>

            <div class="orders-grid" id="ordersGrid">
                <!-- Order cards will be generated by JS -->
            </div>

            <div class="orders-bottom-bar">
                <div class="bottom-search-icon">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </div>
                <div class="bottom-filters">
                    <button class="bottom-filter active" data-type="All">All</button>
                    <button class="bottom-filter" data-type="Delivery">Delivery</button>
                    <button class="bottom-filter" data-type="Pick Up">Pick Up</button>
                </div>
                <button class="order-list-btn" onclick="renderOrders('All', 'All')">Refresh List</button>
            </div>
        </main>
    </div>

    <!-- Order Details Modal -->
    <div id="orderDetailsModal" class="cute-modal-overlay">
        <div class="cute-modal-content" style="max-width: 550px; padding: 30px; text-align: left;">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
                <h3 class="cute-modal-title" style="margin: 0; color: var(--primary-orange);"><i class="fa-solid fa-receipt"></i> Order Details</h3>
                <button onclick="closeOrderDetails()" style="background:none; border:none; font-size:24px; cursor:pointer; color: #888;">&times;</button>
            </div>
            <div id="orderDetailsContent" style="max-height: 400px; overflow-y: auto; padding-right: 10px;"></div>
            <div style="text-align: center; margin-top: 25px;">
                <button class="cute-modal-btn" onclick="closeOrderDetails()">Close</button>
            </div>
        </div>
    </div>

    <script>
        // Use real data from PHP instead of hardcoded data
        const ordersData = <?php echo $orders_json; ?> || [];

        function getActionButtons(order) {
            const status = order.status.toLowerCase();
            if (status === 'pending') {
                return `
                    <button onclick="updateOrderStatus(${order.id}, 'Accepted', event)" style="background:#4CAF50; color:white; border:none; padding:6px 12px; border-radius:15px; cursor:pointer; font-weight:bold; font-size:11px;">Accept</button>
                    <button onclick="updateOrderStatus(${order.id}, 'Rejected', event)" style="background:#F44336; color:white; border:none; padding:6px 12px; border-radius:15px; cursor:pointer; font-weight:bold; font-size:11px;">Reject</button>
                `;
            } else if (status === 'accepted') {
                return `
                    <button onclick="updateOrderStatus(${order.id}, 'Finished', event)" style="background:#2196F3; color:white; border:none; padding:6px 12px; border-radius:15px; cursor:pointer; font-weight:bold; font-size:11px;">Finish</button>
                `;
            }
            return '';
        }

        function updateOrderStatus(orderId, newStatus) {
            fetch('update_order_status.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ order_id: orderId, status: newStatus })
            })
            .then(res => res.json())
            .then(data => {
                if (data.success) {
                    const order = ordersData.find(o => o.id === orderId);
                    if (order) order.status = newStatus;
                    renderOrders(currentStatusFilter, currentTypeFilter);
                } else {
                    alert('Failed to update status: ' + data.message);
                }
            })
            .catch(err => {
                console.error(err);
                alert('Error communicating with server.');
            });
        }

        function viewOrderDetails(orderId) {
            const order = ordersData.find(o => o.id === orderId);
            if (!order) return;
            
            let html = `
                <div style="background: #f9f9f9; padding: 15px; border-radius: 10px; margin-bottom: 20px; font-size: 14px; color: #555;">
                    <p style="margin-bottom: 5px;"><strong>Customer:</strong> ${order.customer}</p>
                    <p style="margin-bottom: 5px;"><strong>Order ID:</strong> #${order.id}</p>
                    <p style="margin-bottom: 5px;"><strong>Type:</strong> ${order.type}</p>
                    <p style="margin-bottom: 5px;"><strong>Payment:</strong> ${order.payment_method}</p>
                    <p style="margin-bottom: 0;"><strong>Instructions:</strong> <em>${order.delivery_instructions || 'None'}</em></p>
                </div>
                <h4 style="margin-bottom: 12px; color: var(--text-dark); border-bottom: 1px solid #eee; padding-bottom: 5px;">Items</h4>
                <ul style="list-style: none; padding: 0; margin: 0;">
            `;
            
            if (order.items && order.items.length > 0) {
                order.items.forEach(item => {
                    html += `
                        <li style="display: flex; justify-content: space-between; align-items: center; padding: 10px 0; border-bottom: 1px solid #eee;">
                            <span style="font-size: 14px; color: #444;">${item.quantity}x ${item.name}</span>
                            <strong style="color: #222;">₱${item.price.toFixed(2)}</strong>
                        </li>
                    `;
                });
            } else {
                html += `<li style="padding: 10px 0; color: #888;">No items found in this order.</li>`;
            }
            
            html += `
                </ul>
                <div style="display: flex; justify-content: space-between; margin-top: 20px; font-size: 18px; font-weight: bold; color: var(--primary-orange);">
                    <span>Total:</span>
                    <span>₱${order.price.toFixed(2)}</span>
                </div>
            `;
            
            document.getElementById('orderDetailsContent').innerHTML = html;
            document.getElementById('orderDetailsModal').classList.add('show');
        }

        function closeOrderDetails() {
            document.getElementById('orderDetailsModal').classList.remove('show');
        }

        function renderOrders(statusFilter = 'All', typeFilter = 'All') {
            const grid = document.getElementById('ordersGrid');
            grid.innerHTML = '';

            const filteredOrders = ordersData.filter(order => {
                const statusMatch = statusFilter === 'All' || order.status === statusFilter;
                const typeMatch = typeFilter === 'All' || order.type === typeFilter;
                return statusMatch && typeMatch;
            });

            if (filteredOrders.length === 0) {
                grid.innerHTML = `<div style="grid-column: 1/-1; text-align: center; color: #888; padding: 50px;">No orders found.</div>`;
                return;
            }

            filteredOrders.forEach(function(order) {
                var statusClass = order.status.toLowerCase();
                
                var card = document.createElement('div');
                card.className = 'order-card-row';
                card.style.cursor = 'pointer';
                card.addEventListener('click', function() { viewOrderDetails(order.id); });

                // Left colored side
                var side = document.createElement('div');
                side.className = 'order-side ' + statusClass;
                side.innerHTML = '<div class="platform-name">' + order.platform + '</div><div class="order-type">' + order.type + '</div>';

                // Right details section
                var details = document.createElement('div');
                details.className = 'order-details';

                // Top row
                var topRow = document.createElement('div');
                topRow.className = 'order-row top-row';
                topRow.innerHTML = '<span class="customer-name">' + order.customer + '</span><span class="order-id">#' + order.id + '</span>';

                // Mid row
                var midRow = document.createElement('div');
                midRow.className = 'order-row mid-row';
                midRow.innerHTML = '<span class="price">&#8369;' + order.price.toFixed(2) + ' <span class="paid-status">(' + order.payment_method + ')</span></span>';

                // Bottom row
                var botRow = document.createElement('div');
                botRow.className = 'order-row bottom-row';
                botRow.innerHTML = '<span class="status-text ' + statusClass + '-text">' + order.status + '</span><span class="time-text ' + statusClass + '-text">' + (order.time !== '-' ? order.time : '') + '</span>';

                // Actions row
                var actionsRow = document.createElement('div');
                actionsRow.className = 'order-actions';
                actionsRow.style.cssText = 'margin-top: 10px; display: flex; gap: 8px; flex-wrap: wrap;';

                // Accept / Reject / Finish buttons
                if (statusClass === 'pending') {
                    var acceptBtn = document.createElement('button');
                    acceptBtn.textContent = 'Accept';
                    acceptBtn.style.cssText = 'background:#4CAF50; color:white; border:none; padding:6px 14px; border-radius:15px; cursor:pointer; font-weight:bold; font-size:11px; transition: transform 0.2s;';
                    acceptBtn.addEventListener('click', function(e) { e.stopPropagation(); updateOrderStatus(order.id, 'Accepted'); });

                    var rejectBtn = document.createElement('button');
                    rejectBtn.textContent = 'Reject';
                    rejectBtn.style.cssText = 'background:#F44336; color:white; border:none; padding:6px 14px; border-radius:15px; cursor:pointer; font-weight:bold; font-size:11px; transition: transform 0.2s;';
                    rejectBtn.addEventListener('click', function(e) { e.stopPropagation(); updateOrderStatus(order.id, 'Rejected'); });

                    actionsRow.appendChild(acceptBtn);
                    actionsRow.appendChild(rejectBtn);
                } else if (statusClass === 'accepted') {
                    var finishBtn = document.createElement('button');
                    finishBtn.textContent = 'Finish';
                    finishBtn.style.cssText = 'background:#2196F3; color:white; border:none; padding:6px 14px; border-radius:15px; cursor:pointer; font-weight:bold; font-size:11px; transition: transform 0.2s;';
                    finishBtn.addEventListener('click', function(e) { e.stopPropagation(); updateOrderStatus(order.id, 'Finished'); });
                    actionsRow.appendChild(finishBtn);
                }

                // View button
                var viewBtn = document.createElement('button');
                viewBtn.textContent = 'View';
                viewBtn.style.cssText = 'background:#eee; color:#444; border:none; padding:6px 15px; border-radius:15px; cursor:pointer; font-weight:bold; font-size:11px; transition: transform 0.2s;';
                viewBtn.addEventListener('click', function(e) { e.stopPropagation(); viewOrderDetails(order.id); });
                actionsRow.appendChild(viewBtn);

                details.appendChild(topRow);
                details.appendChild(midRow);
                details.appendChild(botRow);
                details.appendChild(actionsRow);

                card.appendChild(side);
                card.appendChild(details);
                grid.appendChild(card);
            });
        }

        // Tab Switching
        let currentStatusFilter = 'All';
        let currentTypeFilter = 'All';

        document.querySelectorAll('.order-tab').forEach(tab => {
            tab.addEventListener('click', (e) => {
                const targetTab = e.currentTarget;
                document.querySelectorAll('.order-tab').forEach(t => t.classList.remove('active'));
                targetTab.classList.add('active');
                currentStatusFilter = targetTab.getAttribute('data-status');
                renderOrders(currentStatusFilter, currentTypeFilter);
            });
        });

        // Bottom Filters
        document.querySelectorAll('.bottom-filter').forEach(btn => {
            btn.addEventListener('click', (e) => {
                const targetBtn = e.currentTarget;
                document.querySelectorAll('.bottom-filter').forEach(b => b.classList.remove('active'));
                targetBtn.classList.add('active');
                currentTypeFilter = targetBtn.getAttribute('data-type');
                renderOrders(currentStatusFilter, currentTypeFilter);
            });
        });

        // Time Update
        function updateDateTime() {
            const now = new Date();
            document.getElementById('currentDateTime').textContent = now.toLocaleString();
        }
        setInterval(updateDateTime, 1000);
        updateDateTime();

        // Initial Render
        renderOrders();
    </script>
</body>
</html>
